name: sharely
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Graphics
  animate_do: ^3.3.4
  cupertino_icons: ^1.0.8

  # State Management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6

  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Firebase
  firebase_core: ^3.8.0
  firebase_analytics: ^11.3.5
  firebase_crashlytics: ^4.1.5
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6

  # Packages
  either_dart: ^1.0.0
  envied: ^0.5.4+1
  freezed_annotation: ^2.4.4
  get_it: ^8.0.0
  go_router: ^14.6.1
  http: ^1.2.2
  intl: ^0.19.0
  intl_utils: ^2.8.7
  json_annotation: ^4.9.0

  # Utils
  logger: ^2.4.0
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Code Generation
  build_runner: ^2.4.13
  envied_generator: ^0.5.4+1
  flutter_gen_runner: ^5.7.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true

flutter_intl:
  enabled: true
  class_name: IntlTranslations
  main_locale: es
  arb_dir: lib/i18n
  output_dir: lib/gen

flutter_gen:
  outputs: lib/gen
