name: sharely_ui
description: "UI components for Sharely app"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Code Generation
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  generate: true

flutter_gen:
  outputs: lib/gen